const date = new Date()
        const nap = date.getDay()
        const óra = date.getHours()
        const perc = date.getMinutes()

        let művtKórus = document.getElementById('művtKórus')
        let kamara = document.getElementById('kamara')
        let gitár1 = document.getElementById('gitár1')
        let zir = document.getElementById('zir')
        let aco = document.getElementById('akusztika')
        let gitár2 = document.getElementById('gitár2')
        let conti = document.getElementById('conti')
        let szolf = document.getElementById('szolf')
        let gitZen = document.getElementById('gitárzenekar')
        let prog = document.getElementById('prog')

        let hétfő = document.getElementById("Mon")
        let kedd = document.getElementById("Tue")
        let szerda = document.getElementById("Wed")
        let csütörtök = document.getElementById("Thu")
        let péntek = document.getElementById("Fri")
        let szombat = document.getElementById("Sat")
        let vasárnap = document.getElementById("Sun")